### ISSUE TITLE
FTDI

### ISSUE THREAD

**Issue by Georgelopes21** [rkl099/Appinventor#1]
Is it possible to make a serialotg extension with d2xx.jar that has bitbang setbitmode, support and SetBreakOn, SetBreakOff.

**Comment by rkl099** [comment]
My first attempt was to use D2xx.jar to include FTDI chips in AI2. I worked ok, so it is possible. You still have to refactor Physicaloid library if you want it to work with AI Companion.
You also have to consider D2xx license terms, and that is why its not included in AI2. 
See discussion in https://community.appinventor.mit.edu/t/using-serial-with-ftdi/14136.

The bit-bang modes are probably only used for FTDI chips and not for the other chips in my library so it is not so interesting to add that. 
It was a long time since I heard someone used the break function, but I guess it can be added for all chips, since its a standard Rs232 function. You may also want to include break detection but there is no call back functions in the library.
